from aimai_search import AimaiSearch

print(">>> from aimai_search import AimaiSearch")
aimai = AimaiSearch(["カツカレー", "カツ丼", "カルテット"])
print(">>> aimai = AimaiSearch(['カツカレー', 'カツ丼', 'カルテット'])")
ret = aimai.search("cutlet")
print(">>> aimai.search('cutlet')")
print(ret)
ret = aimai.search("cutlet curry")
print(">>> aimai.search('cutlet curry')")
print(ret)
ret = aimai.search("katsu")
print(">>> aimai.search('katsu')")
print(ret)
ret = aimai.search("don")
print(">>> aimai.search('don')")
print(ret)
ret = aimai.search("丼")
print(">>> aimai.search('丼')")
print(ret)
